---
services:
  traefik:
    image: docker.io/library/traefik:v3.4.0
    container_name: traefik
    command:
      - "--certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL}"
    ports:
      - 8080:8080
      - 8443:443
      - 8444:444
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
      - frontend-noproxy
    restart: unless-stopped

networks:
  frontend:
    external: true
  frontend-noproxy:
    external: true